class_name NodeifyCodeGenerator
extends RefCounted

static func generate(data: NodeifyGraphData, owner: Node = {}) -> String:
	var events: Array[Dictionary] = []
	var others: Array[Dictionary] = []

	for nd in data.nodes:
		var def = NodeifyRegistry.NODE_DEFS.get(nd["type"], {})
		if def.get("category", "") == "events":
			events.append(nd)
		else:
			others.append(nd)

	if events.is_empty():
		return ""

	var lines: PackedStringArray = []
	lines.append("extends Node3D")
	lines.append("")
	lines.append("# Generated by Nodeify")
	lines.append("")

	# Collect variables
	var vars_used: Dictionary = {}
	for nd in data.nodes:
		if nd["type"] == "set_var" or nd["type"] == "get_var":
			vars_used[nd["props"].get("name", "my_var")] = true
	for v in vars_used:
		lines.append("var %s" % v)
	if not vars_used.is_empty():
		lines.append("")

	# Generate _ready, _process, etc.
	for ev in events:
		var ev_type = ev["type"]
		match ev_type:
			"on_ready":
				lines.append("func _ready():")
				lines.append(_generate_body(ev, data, others, "    "))
				lines.append("")
			"on_process":
				lines.append("func _process(delta):")
				lines.append(_generate_body(ev, data, others, "    "))
				lines.append("")
			"on_physics_process":
				lines.append("func _physics_process(delta):")
				lines.append(_generate_body(ev, data, others, "    "))
				lines.append("")
			"on_input":
				lines.append("func _input(event):")
				lines.append(_generate_body(ev, data, others, "    "))
				lines.append("")
			"on_key_pressed":
				var key = ev["props"].get("key", "KEY_SPACE")
				lines.append("func _input(event):")
				lines.append("    if event is InputEventKey and event.pressed and event.keycode == %s:" % key)
				lines.append(_generate_body(ev, data, others, "        "))
				lines.append("")
			_:
				lines.append("func _on_%s():" % ev_type)
				lines.append(_generate_body(ev, data, others, "    "))
				lines.append("")

	return lines.join("\n")

static func _generate_body(event_node: Dictionary, data: NodeifyGraphData, _others: Array, indent: String) -> String:
	var lines: PackedStringArray = []
	var visited: Dictionary = {}
	_trace_exec(event_node["id"], 0, data, lines, indent, visited)
	if lines.is_empty():
		lines.append(indent + "pass")
	return lines.join("\n")

static func _trace_exec(node_id: int, port: int, data: NodeifyGraphData, lines: PackedStringArray, indent: String, visited: Dictionary) -> void:
	var key = "%d:%d" % [node_id, port]
	if visited.has(key):
		return
	visited[key] = true

	var conns = data.get_output_connections(node_id, port)
	for conn in conns:
		var target = data.get_node(conn["to_node"])
		if target.is_empty():
			continue
		_generate_node_code(target, data, lines, indent, visited)

static func _generate_node_code(nd: Dictionary, data: NodeifyGraphData, lines: PackedStringArray, indent: String, visited: Dictionary) -> void:
	var t = nd["type"]
	var props = nd.get("props", {})
	var line = ""

	match t:
		"set_property":
			var prop = props.get("property", "position")
			line = "%s%s.%s = %s" % [indent, _resolve_input(nd, 1, data), prop, _resolve_input(nd, 2, data)]
		"get_property":
			line = "%svar _tmp = %s.%s" % [indent, _resolve_input(nd, 0, data), props.get("property", "position")]
		"set_position_3d":
			line = "%s%s.global_position = %s" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"set_rotation_3d":
			line = "%s%s.rotation = %s" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"set_scale_3d":
			line = "%s%s.scale = %s" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"set_position_2d":
			line = "%s%s.global_position = %s" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"set_rotation_2d":
			line = "%s%s.rotation = %s" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"set_scale_2d":
			line = "%s%s.scale = %s" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"translate":
			line = "%s%s.translate(%s)" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"apply_impulse_3d":
			line = "%s%s.apply_central_impulse(%s)" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"apply_impulse_2d":
			line = "%s%s.apply_central_impulse(%s)" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"move_toward_3d":
			line = "%svar _mt = %s.move_toward(%s, %s)" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data), _resolve_input(nd, 3, data)]
		"look_at_3d":
			line = "%s%s.look_at(%s)" % [indent, _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"set_var":
			line = "%s%s = %s" % [indent, props.get("name", "my_var"), _resolve_input(nd, 1, data)]
		"increment_var":
			line = "%s%s += %s" % [indent, props.get("name", "score"), props.get("amount", 1)]
		"print":
			line = "%sprint(%s)" % [indent, _resolve_input(nd, 1, data)]
		"emit_signal":
			line = "%semit_signal(&\"%s\")" % [indent, props.get("signal_name", "my_signal")]
		"call_method":
			line = "%s%s.%s()" % [indent, _resolve_input(nd, 1, data), props.get("method", "do_thing")]
		"delay":
			line = "%sawait get_tree().create_timer(%s).timeout" % [indent, props.get("seconds", 1.0)]
		"for_loop":
			var count = props.get("count", 10)
			line = "%sfor i in %s:" % [indent, count]
			lines.append(line)
			_trace_exec(nd["id"], 0, data, lines, indent + "    ", visited)
			_trace_exec(nd["id"], 1, data, lines, indent, visited)
			return
		"sequence":
			_trace_exec(nd["id"], 0, data, lines, indent, visited)
			_trace_exec(nd["id"], 1, data, lines, indent, visited)
			_trace_exec(nd["id"], 2, data, lines, indent, visited)
			return
		"if_else":
			line = "%sif %s:" % [indent, _resolve_input(nd, 1, data)]
			lines.append(line)
			_trace_exec(nd["id"], 0, data, lines, indent + "    ", visited)
			lines.append(indent + "else:")
			_trace_exec(nd["id"], 1, data, lines, indent + "    ", visited)
			return
		"return":
			line = "%sreturn %s" % [indent, _resolve_input(nd, 1, data)]
		_:
			line = "%s# TODO: %s" % [indent, t]

	if not line.is_empty():
		lines.append(line)

	_trace_exec(nd["id"], 0, data, lines, indent, visited)

static func _resolve_input(nd: Dictionary, port: int, data: NodeifyGraphData) -> String:
	var def = NodeifyRegistry.NODE_DEFS.get(nd["type"], {})
	var inputs = def.get("inputs", [])
	if port >= inputs.size():
		return "null"

	var conn = data.get_input_connection(nd["id"], port)
	if not conn.is_empty():
		var source = data.get_node(conn["from_node"])
		if not source.is_empty():
			return _get_output_expr(source, conn["from_port"], data)

	var props = nd.get("props", {})
	var prop_keys = ["value", "position", "target", "offset", "impulse", "object", "stream"]
	for pk in prop_keys:
		if props.has(pk):
			return str(props[pk])

	if inputs[port].get("type", "") == "data":
		return "null"
	return "null"

static func _get_output_expr(nd: Dictionary, port: int, data: NodeifyGraphData) -> String:
	var t = nd["type"]
	var props = nd.get("props", {})
	match t:
		"number":
			return str(props.get("value", 0))
		"vector3":
			return "Vector3(%s, %s, %s)" % [_resolve_input(nd, 0, data), _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"vector2":
			return "Vector2(%s, %s)" % [_resolve_input(nd, 0, data), _resolve_input(nd, 1, data)]
		"math_op":
			return "(%s %s %s)" % [_resolve_input(nd, 0, data), props.get("operator", "+"), _resolve_input(nd, 1, data)]
		"math_func":
			return "%s(%s)" % [props.get("function", "abs"), _resolve_input(nd, 0, data)]
		"compare":
			return "(%s %s %s)" % [_resolve_input(nd, 0, data), props.get("operator", "=="), _resolve_input(nd, 1, data)]
		"and_gate":
			return "(%s and %s)" % [_resolve_input(nd, 0, data), _resolve_input(nd, 1, data)]
		"or_gate":
			return "(%s or %s)" % [_resolve_input(nd, 0, data), _resolve_input(nd, 1, data)]
		"not_gate":
			return "not %s" % _resolve_input(nd, 0, data)
		"is_key_pressed":
			return "Input.is_key_pressed(%s)" % props.get("key", "KEY_SPACE")
		"is_action_pressed":
			return "Input.is_action_pressed(\"%s\")" % props.get("action", "ui_accept")
		"is_action_just_pressed":
			return "Input.is_action_just_pressed(\"%s\")" % props.get("action", "ui_accept")
		"get_axis":
			return "Input.get_axis(\"%s\", \"%s\")" % [props.get("negative", "ui_left"), props.get("positive", "ui_right")]
		"lerp":
			return "lerp(%s, %s, %s)" % [_resolve_input(nd, 0, data), _resolve_input(nd, 1, data), _resolve_input(nd, 2, data)]
		"random_range":
			return "randf_range(%s, %s)" % [_resolve_input(nd, 0, data), _resolve_input(nd, 1, data)]
		"get_var":
			return props.get("name", "my_var")
		"get_property":
			return "%s.%s" % [_resolve_input(nd, 0, data), props.get("property", "position")]
		"get_node_3d":
			return "get_node(\"%s\")" % props.get("path", "")
		"get_node_2d":
			return "get_node(\"%s\")" % props.get("path", "")
		"instantiate_scene":
			return "load(\"%s\").instantiate()" % props.get("path", "")
		"instantiate_scene_2d":
			return "load(\"%s\").instantiate()" % props.get("path", "")
		"type_cast":
			return "%s as %s" % [_resolve_input(nd, 0, data), props.get("type", "Node3D")]
		"is_instance_valid":
			return "is_instance_valid(%s)" % _resolve_input(nd, 0, data)
		"null_check":
			return "%s == null" % _resolve_input(nd, 0, data)
		"call_method":
			return "%s.%s()" % [_resolve_input(nd, 1, data), props.get("method", "")]
		_:
			if port == 0:
				return "_%s_result" % t
			return "null"
